name = "wooplans-checkout"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
VILLA_PRODUCT_ID = "prd_n770b0"
DUPLEX_PRODUCT_ID = "prd_krnnh9"
CHARIOW_API_URL = "https://api.chariow.com/v1"

[env.production]
name = "wooplans-checkout"

[env.production.vars]
VILLA_PRODUCT_ID = "prd_n770b0"
DUPLEX_PRODUCT_ID = "prd_krnnh9"
CHARIOW_API_URL = "https://api.chariow.com/v1"
